{application,exercise,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{exercise_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[exercise_app,exercise_sup,hello,pb_messages,test_pb]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
